version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    depends_on:
      - db
    ports:
      - "5001:5001"
    networks:
      - bot-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Mahdi123
      MYSQL_DATABASE: db
      MYSQL_USER: Mahdi
      MYSQL_PASSWORD: Mahdi123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - bot-network

volumes:
  db_data:

networks:
  bot-network:
