jobs:
  darkube_build_telegram-app_mygpt_hamravesh-c14:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: mahdiporheydari/telegram-bot
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push
      run: 'darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME} --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG}} --workdir . --file ./Dockerfile --build-context . '
  darkube_deploy_telegram-app_mygpt_hamravesh-c14:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_telegram-app_mygpt_hamravesh-c14
    runs-on: ubuntu-latest
    steps:
    - name: darkube-cli deploy
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_TELEGRAM_APP_MYGPT_HAMRAVESH_C14}}
        --app-id ${{secrets.APP_ID_TELEGRAM_APP_MYGPT_HAMRAVESH_C14}} --image-tag
        ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
'on':
  push:
    branches:
    - main
